---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: vault
  namespace: REPLACE_NAMESPACE
spec:
  hosts:
  - "vault.REPLACE_DOMAIN_SUFFIX"
  gateways:
  - vault
  http:
  - route:
    - destination:
        host: key-vault-svc
        port:
          number: 80
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: vault
  namespace: REPLACE_NAMESPACE
spec:
  selector:
    istio: ingressgateway-int
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "vault.REPLACE_DOMAIN_SUFFIX"
---
apiVersion: v1
kind: Service
metadata:
  name: key-vault-svc
  namespace: REPLACE_NAMESPACE
  labels:
    app: key-vault
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8200
      name: port8200
  selector:
    app: key-vault
---
apiVersion: REPLACE_API_VERSION 
kind: Deployment
metadata:
  labels:
    app: key-vault
  name: key-vault
  namespace: REPLACE_NAMESPACE
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: key-vault
  template:
    metadata:
      labels:
        app: key-vault
    spec:
      containers:
      - name: key-vault
        image: REPLACE_DOCKER_REPO:REPLACE_IMAGETAG 
        imagePullPolicy: Always
        securityContext:
          capabilities:
            add:
              - IPC_LOCK
        ports:
        - containerPort: 8200
          name: port8200
        volumeMounts:
        - mountPath: "/data/"
          name: data
        env:
        - name: VAULT_EXTERNAL_ADDRESS
          value: "" # TODO: Set vault.stage.bloxinfra.com

        - name: UNSEAL
          value: "true"

        - name: LOG_FORMAT
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: log_format

        - name: LOG_LEVELS
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: log_levels

        - name: LOG_DNS
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: log_dsn

      volumes:
      - persistentVolumeClaim:
          claimName: key-vault
        name: data
