version: '3.7'

services:
  vault:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8200:8200
    volumes:
      - ./data:/data
      - ./policies:/policies
    environment:
      VAULT_CLIENT_TIMEOUT: "30s"
      VAULT_EXTERNAL_ADDRESS: "127.0.0.1"
      UNSEAL: "true"
      # This is needed only for development coz we can't see plugin logs.
      LOG_FORMAT: ${LOG_FORMAT}
      LOG_LEVELS: ${LOG_LEVELS}
      LOG_DSN: ${LOG_DSN}
    cap_add:
      - IPC_LOCK
    restart: unless-stopped
